---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-exec
  namespace: probes-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-exec
  template:
    metadata:
      labels:
        app: liveness-exec
    spec:
      containers:
        - name: liveness-exec
          image: quay.io/lochoa/simple-http-grpc-server
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            exec:
              command:
                - cat
                - ./assets/healthy
            initialDelaySeconds: 5
            periodSeconds: 60
